import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Bricolage_Grotesque, Outfit } from "next/font/google";
import { NavigationLoaderProvider } from "@/components/app-layout/navigation-loader";
import { AuthSessionProvider } from "@/hooks/use-session";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Fabis",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`scroll-smooth ${geist.variable} ${bricolage.variable} ${outfit.variable}`}>
      <body>
        <NavigationLoaderProvider>
          <AuthSessionProvider>
            <TRPCReactProvider>
              {children}
            </TRPCReactProvider>
          </AuthSessionProvider>
        </NavigationLoaderProvider>
      </body>
    </html>
  );
}
